name: e3nn_density
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2.0 # Pytorch import gives error with numpy>=2
  - pytorch
  - pytorch-cuda=12.1
  - pyg
  - pytorch-cluster # not used directly here, ...
  - pytorch-scatter # ...but the model in e3nn requires these
  - e3nn
  - tensorboard
  - plotly
  - cmake # for building gau2grid
  - pip:
    - periodictable
    - gau2grid @ git+https://github.com/dgasmith/gau2grid.git # Pre-built version not available for py3.11